import { toIndexDate } from "../../utils/dateFormat";
import { DayOneFile } from "./types";

/**
 * Parse the JSON file generated by a Day One export and format it as a processable object
 */
export function parseDayOneJson(dayOneJson: DayOneFile): Entries {
	const now = new Date().toString();

	const importEntries: Entries = {};
	dayOneJson.entries.forEach(entry => {
		const { creationDate, text: titleAndText } = entry;

		const indexDate = toIndexDate(new Date(creationDate));

		// Split title and text (if exists)
		let title;
		let text;
		const endOfTitlePos = titleAndText.indexOf("\n\n");
		if (endOfTitlePos <= 0) {
			title = titleAndText;
		} else {
			title = titleAndText.substring(0, endOfTitlePos);
			text = titleAndText.substring(endOfTitlePos + 2);
		}

		// Remove heading formatting from title
		if (title.startsWith("# ")) {
			title = title.substring(2);
		}

		importEntries[indexDate] = {
			dateUpdated: now,
			title,
			text,
		};
	});
	return importEntries;
}
