import { toIndexDate } from "../../utils/dateFormat";

interface JrnlJson {
	tags: Record<string, string>;
	entries: {
		date: string;
		title: string;
		body: string;
		[key: string]: string;
	}[];
}

/**
 * Parse the JSON file generated by a jrnl export and format it as a processable object
 */
export function parseJrnlJson(jrnlJsonStr: string): Entries {
	const jrnlJson = JSON.parse(jrnlJsonStr) as JrnlJson;
	const jrnlEntries = jrnlJson.entries;
	const now = new Date().toString();

	const importEntries: Entries = {};
	jrnlEntries.forEach(entry => {
		const indexDate = toIndexDate(new Date(entry.date));
		let title = entry.title.trim();
		let text = entry.body.trim();

		// Add title and text to existing entry if already is one for the same day
		if (indexDate in importEntries) {
			const existingEntry = { ...importEntries[indexDate] };
			if (existingEntry.title) {
				title = `${existingEntry.text} | ${title}`;
			}
			if (existingEntry.text) {
				text = `${existingEntry.text}\n\n----------\n\n${text}`;
			}
		}

		importEntries[indexDate] = {
			dateUpdated: now,
			title,
			text,
		};
	});
	return importEntries;
}
