import { toIndexDate } from '../dateFormat';

/**
 * Parse the JSON file generated by a jrnl export and format it as a processable object
 */
export function parseJrnlJson(jrnlJsonStr) {
	const jrnlJson = JSON.parse(jrnlJsonStr);
	const { entries } = jrnlJson;
	const now = new Date().toString();

	const importObj = {};
	entries.forEach(entry => {
		const indexDate = toIndexDate(entry.date);
		let title = entry.title.trim();
		let text = entry.body.trim();

		// Add title and text to existing entry if already is one for the same day
		if (indexDate in importObj) {
			const existingEntry = { ...importObj[indexDate] };
			if (existingEntry.title) {
				title = `${existingEntry.text} | ${title}`;
			}
			if (existingEntry.text) {
				text = `${existingEntry.text}\n\n----------\n\n${text}`;
			}
		}

		importObj[indexDate] = {
			dateUpdated: now,
			title,
			text
		};
	});
	return importObj;
}
