import { formatDate } from '../dateUtils';


/**
 * Parse the JSON file generated by a jrnl export and format it as a processable object
 */
export function parseJrnlJson(jrnlJsonStr) {
	const jrnlJson = JSON.parse(jrnlJsonStr);
	const { entries } = jrnlJson;
	const now = new Date().toString();

	const importObj = {};
	entries.forEach((entry) => {
		const dateFormatted = formatDate(entry.date);
		let title;
		let text;
		if (dateFormatted in importObj) {
			// Add to existing entry if there is another one for the day
			const existingEntry = { ...importObj[dateFormatted] };
			// Append new title to existing one
			if (existingEntry.title) {
				title = `${existingEntry.text} | ${entry.title}`;
			} else {
				({ title } = entry);
			}
			// Append new text to existing one
			if (existingEntry.text) {
				text = `${existingEntry.text}\n\n----------\n\n${entry.body}`;
			} else {
				text = entry.body;
			}
		} else {
			({ title, body: text } = entry);
		}

		importObj[dateFormatted] = {
			dateUpdated: now,
			title,
			text
		};
	});
	return importObj;
}
